name: Create Release

on:
  pull_request:
    # PRが閉じたタイミングで実行
    types:
      - closed
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    
    - run: echo "RELEASE_FILENAME=test_${{ github.event.pull_request.title }}.zip" >> $GITHUB_ENV
      
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: ${{ env.RELEASE_FILENAME }}
        path: './compress'
        exclusions: '*.git*'
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.pull_request.title }}
        name: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.body }}
        draft: false
        prerelease: false
        files: ${{ env.RELEASE_FILENAME }}
